# Generated by Django 4.0.5 on 2022-06-30 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_content_based'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
